name: Publish Linux build image

on:
  push:
    paths:
    - '.github/workflows/linux_build.yml'
    - 'build/linux/**'
  pull_request:
    paths:
    - '.github/workflows/linux_build.yml'
    - 'build/linux/**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/scp-fs2open/linux_build
          tags: |
            type=sha

      - name: Login to GitHub Docker Registry
        if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
          context: './build/linux'
          platforms: linux/amd64,linux/arm64
          file: './build/linux/Dockerfile'
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
